### ISSUE TITLE
Cannot read property 'products' of null

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby-starter-shopify#24]
I just forked the starter, followed the readme and I am having this issue.

<img width="1240" alt="Screenshot 2021-06-10 at 14 08 47" src="https://user-images.githubusercontent.com/6626225/121522567-8b874280-c9f5-11eb-8c67-57e03033255b.png">

Anyone experiencing the same issue?

**Comment by PolGuixe** [comment]
I have tested with different store credentials and it doesn't work either.

**Comment by cotrimelias** [comment]
I am having the same issue! I posted it before and nothing seems to work

**Comment by dan-thesill** [comment]
I ran into this as well, I think the issue is here:
https://github.com/gatsbyjs/gatsby-starter-shopify/blob/cbc6c7665bee9180473289af011307c63506e040/src/pages/index.jsx#L13-L20

If you don't have a collection using `frontpage` as a handle, the query will fail.

To solve, create a collection with that handle or update to one that does exist.

**Comment by PolGuixe** [comment]
@dan-thesill you are right!

There is an issue with Shopify handles, I believe that once is deleted it is difficult to recover it. I just changed `frontpage` to `frontpage1` and created the collection in Shopify.
